/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.View;

import com.mycompany.DomainModels.ChucVu;
import com.mycompany.Service.ChucVuSevice;
import com.mycompany.Service.IPM.ChucVuServiceImp;
import com.mycompany.Service.IPM.NhanVienServiceIpm;
import com.mycompany.Service.NhanVienService;
import com.mycompany.ViewModel.NhanVien.NhanVienViewModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kunrl
 */
public class NhanVienPanel extends javax.swing.JPanel {

   ChucVuSevice svcv = new ChucVuServiceImp();
    NhanVienService svnv = new NhanVienServiceIpm();
    
    public NhanVienPanel() {
        initComponents();
         loadChucVu();
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        btnThungRac = new javax.swing.JButton();
        btnsua = new javax.swing.JButton();
        byaxoa = new javax.swing.JButton();
        btnmoi = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        rdnam = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        rdnu = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        txttentk = new javax.swing.JTextField();
        txtmatkhau = new javax.swing.JPasswordField();
        txtsdt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtdiachi = new javax.swing.JTextArea();
        btnshowmk = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        cbtrangthai = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbchucvu = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnthem = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtma = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbnhavien = new javax.swing.JTable();
        txttimkiem = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        txtten = new javax.swing.JTextField();

        btnThungRac.setBackground(new java.awt.Color(255, 0, 51));
        btnThungRac.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete.png"))); // NOI18N
        btnThungRac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThungRacActionPerformed(evt);
            }
        });

        btnsua.setBackground(new java.awt.Color(153, 255, 153));
        btnsua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/refresh.png"))); // NOI18N
        btnsua.setText("Sửa");
        btnsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuaActionPerformed(evt);
            }
        });

        byaxoa.setBackground(new java.awt.Color(153, 255, 153));
        byaxoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btnRemove.png"))); // NOI18N
        byaxoa.setText("Xóa");
        byaxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                byaxoaActionPerformed(evt);
            }
        });

        btnmoi.setBackground(new java.awt.Color(153, 255, 153));
        btnmoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reload.png"))); // NOI18N
        btnmoi.setText("Làm mới");
        btnmoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmoiActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(153, 255, 153));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdnam);
        rdnam.setSelected(true);
        rdnam.setText("Nam");

        jLabel3.setText("Họ tên");

        buttonGroup1.add(rdnu);
        rdnu.setText("Nữ");

        jLabel4.setText("Tên tài khoản");

        jLabel5.setText("Mật khẩu");

        txtdiachi.setColumns(20);
        txtdiachi.setRows(5);
        jScrollPane2.setViewportView(txtdiachi);

        btnshowmk.setBackground(new java.awt.Color(153, 255, 153));
        btnshowmk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnshowmkActionPerformed(evt);
            }
        });

        jLabel6.setText("Giới tính");

        cbtrangthai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đang làm", "Đã nghỉ" }));
        cbtrangthai.setName(""); // NOI18N

        jLabel7.setText("SDT");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Nhân Viên");

        jLabel8.setText("Chức vụ");

        jLabel9.setText("Trạng thái");

        jLabel2.setText("Mã");

        btnthem.setBackground(new java.awt.Color(153, 255, 153));
        btnthem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/addSanPham.png"))); // NOI18N
        btnthem.setText("Thêm ");
        btnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemActionPerformed(evt);
            }
        });

        jLabel10.setText("Dịa chỉ");

        jPanel1.setBackground(new java.awt.Color(102, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        tbnhavien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã", "Họ tên", "Tên tài khoàn", "Mật khẩu", "Giơi tính", "Đia Chỉ", "SĐT", "Chức Vụ", "Trạng Thái"
            }
        ));
        tbnhavien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbnhavienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbnhavien);

        txttimkiem.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txttimkiemCaretUpdate(evt);
            }
        });
        txttimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttimkiemActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(153, 255, 153));
        jButton3.setText("Tìm kiếm");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txttimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addGap(38, 38, 38))
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txttimkiem)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(412, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnThungRac, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(402, 402, 402))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createSequentialGroup()
                    .addGap(182, 182, 182)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(266, 266, 266)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtma, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3))
                            .addGap(133, 133, 133)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtsdt, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(101, 101, 101)
                            .addComponent(btnthem, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtten, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4))
                            .addGap(133, 133, 133)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(cbchucvu, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(100, 100, 100)
                            .addComponent(btnsua, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txttentk, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5))
                            .addGap(133, 133, 133)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cbtrangthai, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(100, 100, 100)
                            .addComponent(byaxoa, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtmatkhau, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnshowmk, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(rdnam, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(33, 33, 33)
                                    .addComponent(rdnu)))
                            .addGap(61, 61, 61)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(101, 101, 101)
                            .addComponent(btnmoi, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(174, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(135, 135, 135)
                .addComponent(btnThungRac)
                .addContainerGap(493, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(125, 125, 125)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel7))
                    .addGap(8, 8, 8)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(20, 20, 20)
                                    .addComponent(jLabel3))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtsdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(20, 20, 20)
                                    .addComponent(jLabel8)))
                            .addGap(6, 6, 6)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(27, 27, 27)
                                    .addComponent(jLabel4))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(cbchucvu)
                                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(22, 22, 22)
                                    .addComponent(jLabel9))))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnthem, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(29, 29, 29)
                            .addComponent(btnsua, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(txttentk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel5))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(3, 3, 3)
                            .addComponent(cbtrangthai, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel10))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(byaxoa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(2, 2, 2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtmatkhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnshowmk))
                            .addGap(17, 17, 17)
                            .addComponent(jLabel6)
                            .addGap(6, 6, 6)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(rdnam)
                                .addComponent(rdnu)))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(22, 22, 22)
                            .addComponent(btnmoi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(21, 21, 21)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnThungRacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThungRacActionPerformed
        ThungRacNVForm trnv = new ThungRacNVForm();
        trnv.setVisible(true);
    }//GEN-LAST:event_btnThungRacActionPerformed

    private void btnsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuaActionPerformed
        // TODO add your handling code here:
        int row = tbnhavien.getSelectedRow();

        if (row == - 1) {
            JOptionPane.showMessageDialog(this, "Moi chon dong");
            return;
        }
        NhanVienViewModel nv = getFrom();

        if (svnv.updateNhanVien(nv.getMa(), nv) != null) {
            JOptionPane.showMessageDialog(this, "Sửa thành công");
        } else {
            JOptionPane.showMessageDialog(this, "Sửa thành công");
        }
        loadData();
    }//GEN-LAST:event_btnsuaActionPerformed

    private void byaxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_byaxoaActionPerformed
        // TODO add your handling code here:
        int row = tbnhavien.getSelectedRow();

        if (row == - 1) {
            JOptionPane.showMessageDialog(this, "Moi chon dong");
            return;
        }

        int comfirm = JOptionPane.showConfirmDialog(this, "Xác nhận xóa");
        if (comfirm != JOptionPane.YES_OPTION) {
            return;
        }
        String ma = tbnhavien.getValueAt(row, 0).toString();

        svnv.UpdateThungRacNV(ma);
        loadData();
    }//GEN-LAST:event_byaxoaActionPerformed

    private void btnmoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmoiActionPerformed
        // TODO add your handling code here:
        txtma.setText("");
        txtten.setText("");
        txttentk.setText("");
        txtmatkhau.setText("");
        txtdiachi.setText("");
        txtsdt.setText("");
        cbchucvu.setSelectedItem("");
        cbtrangthai.setSelectedItem("");
        txtma.setText("");
        rdnam.setSelected(true);
    }//GEN-LAST:event_btnmoiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new ChucVuFrom().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnshowmkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnshowmkActionPerformed
        // TODO add your handling code here:
        if (btnshowmk.isSelected()) {
            txtmatkhau.setEchoChar((char) 0);
        } else {
            txtmatkhau.setEchoChar('*');
        }
    }//GEN-LAST:event_btnshowmkActionPerformed

    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed
        // TODO add your handling code here:
        NhanVienViewModel nv = getFrom();

        if (svnv.InsertNhanVien(nv) != null) {
            JOptionPane.showMessageDialog(this, "Thêm thành công");
        } else {
            JOptionPane.showMessageDialog(this, "Sửa thành công");
        }
        loadData();
    }//GEN-LAST:event_btnthemActionPerformed

    private void tbnhavienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbnhavienMouseClicked
        // TODO add your handling code here:
        int row = tbnhavien.getSelectedRow();
        String ma = tbnhavien.getValueAt(row, 0).toString();
        String ten = tbnhavien.getValueAt(row, 1).toString();
        String tentk = tbnhavien.getValueAt(row, 2).toString();
        String mk = tbnhavien.getValueAt(row, 3).toString();
        // String gt = tbnhavien.getValueAt(row, 4).toString();
        String diachi = tbnhavien.getValueAt(row, 5).toString();
        String sdt = tbnhavien.getValueAt(row, 6).toString();
        String cv = tbnhavien.getValueAt(row, 7).toString();
        String tt = tbnhavien.getValueAt(row, 8).toString();

        txtma.setText(ma);
        txtten.setText(ten);
        txttentk.setText(tentk);
        txtmatkhau.setText(mk);
        txtdiachi.setText(diachi);
        txtsdt.setText(sdt);
        cbchucvu.setSelectedItem(cv);
        cbtrangthai.setSelectedItem(tt);
        txtma.setText(ma);
        if (tbnhavien.getValueAt(row, 4).toString().equals("Nam")) {
            rdnam.setSelected(true);
        } else {
            rdnu.setSelected(true);
        }
    }//GEN-LAST:event_tbnhavienMouseClicked

    private void txttimkiemCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txttimkiemCaretUpdate
        // TODO add your handling code here:
        //        String timkiem;
        //        timkiem = txttimkiem.getText();
        //        DefaultTableModel de = (DefaultTableModel) tbnhavien.getModel();
        //        de.setRowCount(0);
        //        NhanVienViewModel nv = svnv.getseach(timkiem);
        //        de.addRow(new Object[]{
            //            nv.getMa(), nv.getHoTen(), nv.getTenTK(), nv.getMatKhau(),
            //            nv.getGioiTinh(), nv.getDiaChi(),
            //            nv.getSdt(), nv.getTencv(), nv.gettrangthai()
            //        });
    }//GEN-LAST:event_txttimkiemCaretUpdate

    private void txttimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttimkiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttimkiemActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String timkiem;
        if (txttimkiem.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Mời bạn nhập mã nhân viên");
        } else {
            timkiem = txttimkiem.getText();
            DefaultTableModel de = (DefaultTableModel) tbnhavien.getModel();
            de.setRowCount(0);
            NhanVienViewModel nv = svnv.getByMa(timkiem);
            de.addRow(new Object[]{
                nv.getMa(), nv.getHoTen(), nv.getTenTK(), nv.getMatKhau(),
                nv.getGioiTinh(), nv.getDiaChi(),
                nv.getSdt(), nv.getTencv(), nv.gettrangthai()
            });

        }
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThungRac;
    private javax.swing.JButton btnmoi;
    private javax.swing.JCheckBox btnshowmk;
    private javax.swing.JButton btnsua;
    private javax.swing.JButton btnthem;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton byaxoa;
    private javax.swing.JComboBox<String> cbchucvu;
    private javax.swing.JComboBox<String> cbtrangthai;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rdnam;
    private javax.swing.JRadioButton rdnu;
    private javax.swing.JTable tbnhavien;
    private javax.swing.JTextArea txtdiachi;
    private javax.swing.JTextField txtma;
    private javax.swing.JPasswordField txtmatkhau;
    private javax.swing.JTextField txtsdt;
    private javax.swing.JTextField txtten;
    private javax.swing.JTextField txttentk;
    private javax.swing.JTextField txttimkiem;
    // End of variables declaration//GEN-END:variables
  private void loadChucVu() {
        cbchucvu.removeAllItems();
        for (ChucVu cv : svcv.getListChucVu()) {
            cbchucvu.addItem(cv.getTen());
        }
    }

    private void loadData() {
        DefaultTableModel de = (DefaultTableModel) tbnhavien.getModel();
        de.setRowCount(0);
        for (NhanVienViewModel nv : svnv.getListNhanVien()) {
            de.addRow(new Object[]{
                nv.getMa(), nv.getHoTen(), nv.getTenTK(), nv.getMatKhau(),
                nv.getGioiTinh(), nv.getDiaChi(),
                nv.getSdt(), nv.getTencv(), nv.gettrangthai()
            });
        }
    }

    public NhanVienViewModel getFrom() {
        NhanVienViewModel nv = new NhanVienViewModel();
        nv.setMa(txtma.getText().trim());
        nv.setHoTen(txtten.getText().trim());
        nv.setTenTK(txttentk.getText().trim());
        nv.setMatKhau(txtmatkhau.getText().trim());
        //nv.setGioiTinh(rdnam.equals("") ? "Nam" : "Nu");
        nv.setGioiTinh(rdnam.isSelected() ? "Nam" : "Nữ");

        nv.setDiaChi(txtdiachi.getText());
        nv.setSdt(txtsdt.getText().trim());
        nv.setTrangThai(cbtrangthai.getSelectedIndex());

        ChucVu cv = svcv.getListChucVu().get(cbchucvu.getSelectedIndex());
        nv.setTencv(cv);

        return nv;
    }
    

}
