package com.mycompany.View;

import com.mycompany.DomainModels.HoaDon;
import com.mycompany.DomainModels.ThongKe;
import com.mycompany.Service.HoaDonService;
import com.mycompany.Service.IPM.HoaDonServiceIpm;
import com.mycompany.Service.IPM.ThongKeServiceImp;

import com.mycompany.Service.ThongKeService;
import com.mycompany.ViewModel.BanHang.HoaDonViewModels;
import com.mycompany.ViewModel.ThongKe.ThongKeViewModel;
import java.awt.CardLayout;
import java.awt.Dimension;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellType;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.category.DefaultCategoryDataset;

public class ThongKePanel extends javax.swing.JPanel {

    private HoaDonService hdservice = new HoaDonServiceIpm();
    private Date date;
    ThongKeService thongkeser = new ThongKeServiceImp();

    public ThongKePanel() {
        initComponents();
        loadData();
        TongTien();
        NamHienNay();
        thangHienTai();
        ngayHienTai();
        loadTableSPsapHet();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblngay = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        lblDTNgayThanhcong = new javax.swing.JLabel();
        lblDTNgayHuy = new javax.swing.JLabel();
        lblTHDNgay = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        lblNgayDHT = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblthang = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        lblDTThangThanhcong = new javax.swing.JLabel();
        lblDTThangHuy = new javax.swing.JLabel();
        lblTHDThang = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        lblThangDHT = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblnam = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblDTNamThanhcong = new javax.swing.JLabel();
        lblDTNamHuy = new javax.swing.JLabel();
        lblTHDNam = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        lblNamDHT = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lbltong = new javax.swing.JLabel();
        lblhdThanhcong = new javax.swing.JLabel();
        lblhdHuy = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        lblTHD = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        lblTongDHT = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        pnlDoanhThu = new javax.swing.JPanel();
        pnlBang = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbdoanhthu = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        rdbieudo = new javax.swing.JRadioButton();
        rdbang = new javax.swing.JRadioButton();
        cbtrangthai = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txtngayBD = new com.toedter.calendar.JDateChooser();
        lblmin = new javax.swing.JLabel();
        lblmax = new javax.swing.JLabel();
        txtngayKT = new com.toedter.calendar.JDateChooser();
        btntimkiem = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblThongKeSP = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel3.setBackground(new java.awt.Color(102, 255, 255));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setForeground(new java.awt.Color(240, 240, 240));
        jPanel3.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Tổng Doanh Thu Ngày");

        lblngay.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblngay.setForeground(new java.awt.Color(153, 0, 51));
        lblngay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblngay.setText(" 0 VND");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel17.setText("Tổng Hóa Đơn:");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel19.setText("Thành Công:");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel20.setText("Bị Hủy:");

        lblDTNgayThanhcong.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblDTNgayThanhcong.setForeground(new java.awt.Color(0, 204, 51));
        lblDTNgayThanhcong.setText(" 0 Đơn");

        lblDTNgayHuy.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblDTNgayHuy.setForeground(new java.awt.Color(255, 0, 51));
        lblDTNgayHuy.setText(" 0 Đơn");

        lblTHDNgay.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblTHDNgay.setForeground(new java.awt.Color(255, 0, 255));
        lblTHDNgay.setText("0 Đơn");

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel25.setText("Đơn Giao Hoàn Thành:");

        lblNgayDHT.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblNgayDHT.setText(" 0 Đơn");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblngay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLabel1))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblTHDNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel19)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblDTNgayThanhcong, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel20)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblDTNgayHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel25)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblNgayDHT, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 14, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblngay, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(lblTHDNgay))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(lblDTNgayThanhcong))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(lblDTNgayHuy))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(lblNgayDHT))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(204, 255, 204));
        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 153));
        jLabel2.setText("Tổng Doanh Thu Tháng");

        lblthang.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblthang.setForeground(new java.awt.Color(153, 0, 51));
        lblthang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblthang.setText(" 0 VND");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel16.setText("Tổng Hóa Đơn:");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel21.setText("Bị Hủy:");

        lblDTThangThanhcong.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblDTThangThanhcong.setForeground(new java.awt.Color(0, 204, 51));
        lblDTThangThanhcong.setText(" 0 Đơn");

        lblDTThangHuy.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblDTThangHuy.setForeground(new java.awt.Color(255, 0, 51));
        lblDTThangHuy.setText(" 0 Đơn");

        lblTHDThang.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblTHDThang.setForeground(new java.awt.Color(255, 0, 255));
        lblTHDThang.setText("0 Đơn");

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel24.setText("Thành Công:");

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel26.setText("Đơn Giao Hoàn Thành:");

        lblThangDHT.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblThangDHT.setText(" 0 Đơn");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel2))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTHDThang, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblthang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel24)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblDTThangThanhcong, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel21)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblDTThangHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblThangDHT, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblthang, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(lblTHDThang))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(lblDTThangThanhcong))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDTThangHuy)
                    .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblThangDHT)
                    .addComponent(jLabel26))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(204, 204, 255));
        jPanel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 255));
        jLabel3.setText("Tổng Doanh Thu Năm");

        lblnam.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblnam.setForeground(new java.awt.Color(153, 0, 51));
        lblnam.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblnam.setText(" 0 VND");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel13.setText("Tổng Hóa Đơn:");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel15.setText("Bị Hủy:");

        lblDTNamThanhcong.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblDTNamThanhcong.setForeground(new java.awt.Color(0, 204, 51));
        lblDTNamThanhcong.setText(" 0 Đơn");

        lblDTNamHuy.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblDTNamHuy.setForeground(new java.awt.Color(255, 0, 51));
        lblDTNamHuy.setText(" 0 Đơn");

        lblTHDNam.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblTHDNam.setForeground(new java.awt.Color(255, 0, 255));
        lblTHDNam.setText("0 Đơn");

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel23.setText("Thành Công:");

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel27.setText("Đơn Giao Hoàn Thành:");

        lblNamDHT.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblNamDHT.setText(" 0 Đơn");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblnam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblDTNamHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel23)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblDTNamThanhcong, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel3))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTHDNam, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNamDHT, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblnam, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(lblTHDNam))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDTNamThanhcong)
                    .addComponent(jLabel23))
                .addGap(10, 10, 10)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(lblDTNamHuy))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNamDHT)
                    .addComponent(jLabel27))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 204));
        jPanel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 51));
        jLabel4.setText("Tổng Doanh Thu");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel10.setText("Thành Công:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel11.setText("Bị Hủy : ");

        lbltong.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbltong.setForeground(new java.awt.Color(153, 0, 51));
        lbltong.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltong.setText("0 VND");

        lblhdThanhcong.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblhdThanhcong.setForeground(new java.awt.Color(0, 204, 51));
        lblhdThanhcong.setText(" 0 Đơn");

        lblhdHuy.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblhdHuy.setForeground(new java.awt.Color(255, 0, 51));
        lblhdHuy.setText(" 0 Đơn");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel22.setText("Tổng Hóa Đơn:");

        lblTHD.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblTHD.setForeground(new java.awt.Color(255, 0, 255));
        lblTHD.setText("0 Đơn");

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel28.setText("Đơn Giao Hoàn Thành:");

        lblTongDHT.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblTongDHT.setText(" 0 Đơn");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbltong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTHD, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblhdHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(26, 26, 26))
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(jLabel28)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblTongDHT, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblhdThanhcong, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 16, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbltong, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTHD)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(lblhdThanhcong))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(lblhdHuy))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTongDHT)
                    .addComponent(jLabel28))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );

        jTabbedPane1.setForeground(new java.awt.Color(51, 51, 255));
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        pnlDoanhThu.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlDoanhThu.setLayout(new java.awt.BorderLayout());

        pnlBang.setForeground(new java.awt.Color(240, 240, 240));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(452, 350));

        tbdoanhthu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Số HD", "Ngày ", "Doanh Thu", "Trang Thai"
            }
        ));
        jScrollPane1.setViewportView(tbdoanhthu);

        javax.swing.GroupLayout pnlBangLayout = new javax.swing.GroupLayout(pnlBang);
        pnlBang.setLayout(pnlBangLayout);
        pnlBangLayout.setHorizontalGroup(
            pnlBangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 835, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlBangLayout.setVerticalGroup(
            pnlBangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
        );

        pnlDoanhThu.add(pnlBang, java.awt.BorderLayout.CENTER);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 102, 102));
        jLabel7.setText("THỐNG KÊ DOANH THU");

        jPanel9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton2.setBackground(new java.awt.Color(153, 153, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 153, 153));
        jButton2.setText("Xuất Báo Cáo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdbieudo);
        rdbieudo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rdbieudo.setText("Biểu đồ");
        rdbieudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbieudoActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdbang);
        rdbang.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rdbang.setSelected(true);
        rdbang.setText("Bảng");
        rdbang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbangActionPerformed(evt);
            }
        });

        cbtrangthai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất Cả", "Đã Thành Toán", "Đơn Giao Hoàn Thành", "Đã Hủy" }));
        cbtrangthai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbtrangthaiActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel8.setText("Trạng Thái");

        txtngayBD.setDateFormatString("yyyy-MM-dd");
        txtngayBD.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        lblmin.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblmin.setText("Ngày Bắt Đầu:");

        lblmax.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblmax.setText("Ngày Kết Thúc:");

        txtngayKT.setDateFormatString("yyyy-MM-dd");

        btntimkiem.setBackground(new java.awt.Color(51, 255, 51));
        btntimkiem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btntimkiem.setText("Tìm Kiếm");
        btntimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntimkiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(24, 24, 24)
                        .addComponent(cbtrangthai, 0, 133, Short.MAX_VALUE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(rdbang)
                        .addGap(18, 18, 18)
                        .addComponent(rdbieudo, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblmax)
                            .addComponent(lblmin, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtngayBD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(btntimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtngayKT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbang)
                    .addComponent(rdbieudo))
                .addGap(28, 28, 28)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblmin, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtngayBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblmax, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtngayKT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btntimkiem)
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbtrangthai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(35, 35, 35)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlDoanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, 861, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(381, 381, 381))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlDoanhThu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Doanh Thu", jPanel2);

        jPanel8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 102, 102));
        jLabel6.setText("Danh Sách Sản Phẩm Sắp Hết Hàng");

        tblThongKeSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã SP", "Tên SP", "Màu Sắc", "Nhà Cung Cấp", "Nhà Sản Xuất", "Háng", "Số Lượng", "Size", "Giá Nhập", "Giá Bán"
            }
        ));
        jScrollPane2.setViewportView(tblThongKeSP);

        jTextField1.setText("Tìm Kiếm");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(390, 390, 390)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1021, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(40, 40, 40)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Sản Phẩm", jPanel7);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btntimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntimkiemActionPerformed
        // TODO add your handling code here:

        try {
            finByKhoangNgayThanhToan(txtngayBD.getDate(), txtngayKT.getDate());
        } catch (Exception e) {
        }

    }//GEN-LAST:event_btntimkiemActionPerformed

    private void rdbangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbangActionPerformed
        // TODO add your handling code here:
        pnlBang.removeAll();

        this.pnlBang.add(jScrollPane1);
        loadData();
        //this.pnlBang.add(tbdoanhthu);
    }//GEN-LAST:event_rdbangActionPerformed

    private void rdbieudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbieudoActionPerformed
        // TODO add your handling code here:
        pnlBang.removeAll();
        this.setdatetoChar(pnlBang);
    }//GEN-LAST:event_rdbieudoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            XSSFWorkbook worbook = new XSSFWorkbook();
            XSSFSheet sheet = worbook.createSheet("Doanh Thu");

            XSSFRow row = null;
            Cell cell = null;

            row = sheet.createRow(3);
            cell = row.createCell(0, CellType.NUMERIC);
            cell.setCellValue("STT");

            cell = row.createCell(1, CellType.STRING);
            cell.setCellValue("MaHD");

            cell = row.createCell(2, CellType.STRING);
            cell.setCellValue("Ngày Thanh Toán");

            cell = row.createCell(3, CellType.STRING);
            cell.setCellValue("Tổng Tiền");

            cell = row.createCell(4, CellType.STRING);
            cell.setCellValue("Trạng Thái");

            List<HoaDonViewModels> list = hdservice.GetListHoaSon();

            if (list != null) {
                int s = list.size();
                for (int i = 0; i < s; i++) {
                    HoaDonViewModels hd = list.get(i);
                    row = sheet.createRow(4 + i);

                    cell = row.createCell(0, CellType.NUMERIC);
                    cell.setCellValue(i + 1);
                    cell = row.createCell(01, CellType.STRING);
                    cell.setCellValue(hd.getMa());

                    cell = row.createCell(02, CellType.STRING);
                    cell.setCellValue(hd.getNgayThanhToan().toString());

                    cell = row.createCell(03, CellType.STRING);
                    cell.setCellValue(hd.getTongTien().toString());

                    cell = row.createCell(04, CellType.STRING);
                    cell.setCellValue(hd.getTrangThai().toString());

                }
                File f = new File("F:\\FileThongKe.xlsx");
                try {
                    FileOutputStream fis = new FileOutputStream(f);

                    worbook.write(fis);
                    fis.close();
                } catch (FileNotFoundException e) {
                    e.printStackTrace();
                }
            }
        } catch (Exception ex) {
            ex.printStackTrace();

        }
        JOptionPane.showMessageDialog(this, "Xuất Thành Công");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cbtrangthaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbtrangthaiActionPerformed
        String timkiem = (String) cbtrangthai.getSelectedItem();
        DefaultTableModel de = (DefaultTableModel) tbdoanhthu.getModel();
        if (timkiem == "Tất Cả") {
            de.setRowCount(0);
            for (HoaDonViewModels hd : hdservice.GetListHoaSon()) {
                de.addRow(new Object[]{
                    hd.getMa(), hd.getNgayThanhToan(), hd.getTongTien(), hd.getTrangThai()
                });
            }
        } else if (timkiem == "Đã Thành Toán") {
            de.setRowCount(0);
            for (HoaDonViewModels hd : hdservice.finbyngaytrangThai(5)) {
                de.addRow(new Object[]{
                    hd.getMa(), hd.getNgayThanhToan(), hd.getTongTien(), hd.getTrangThai()
                });
            }
        } else if (timkiem == "Đơn Giao Hoàn Thành") {
            de.setRowCount(0);
            for (HoaDonViewModels hd : hdservice.finbyngaytrangThai(4)) {
                de.addRow(new Object[]{
                    hd.getMa(), hd.getNgayThanhToan(), hd.getTongTien(), hd.getTrangThai()
                });
            }
        }  else {
            de.setRowCount(0);
            for (HoaDonViewModels hd : hdservice.finbyngaytrangThai(2)) {
                de.addRow(new Object[]{
                    hd.getMa(), hd.getNgayThanhToan(), hd.getTongTien(), hd.getTrangThai()
                });
            }
        }

    }//GEN-LAST:event_cbtrangthaiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btntimkiem;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbtrangthai;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblDTNamHuy;
    private javax.swing.JLabel lblDTNamThanhcong;
    private javax.swing.JLabel lblDTNgayHuy;
    private javax.swing.JLabel lblDTNgayThanhcong;
    private javax.swing.JLabel lblDTThangHuy;
    private javax.swing.JLabel lblDTThangThanhcong;
    private javax.swing.JLabel lblNamDHT;
    private javax.swing.JLabel lblNgayDHT;
    private javax.swing.JLabel lblTHD;
    private javax.swing.JLabel lblTHDNam;
    private javax.swing.JLabel lblTHDNgay;
    private javax.swing.JLabel lblTHDThang;
    private javax.swing.JLabel lblThangDHT;
    private javax.swing.JLabel lblTongDHT;
    private javax.swing.JLabel lblhdHuy;
    private javax.swing.JLabel lblhdThanhcong;
    private javax.swing.JLabel lblmax;
    private javax.swing.JLabel lblmin;
    private javax.swing.JLabel lblnam;
    private javax.swing.JLabel lblngay;
    private javax.swing.JLabel lblthang;
    private javax.swing.JLabel lbltong;
    private javax.swing.JPanel pnlBang;
    private javax.swing.JPanel pnlDoanhThu;
    private javax.swing.JRadioButton rdbang;
    private javax.swing.JRadioButton rdbieudo;
    private javax.swing.JTable tbdoanhthu;
    private javax.swing.JTable tblThongKeSP;
    private com.toedter.calendar.JDateChooser txtngayBD;
    private com.toedter.calendar.JDateChooser txtngayKT;
    // End of variables declaration//GEN-END:variables

    private void loadData() {
        DefaultTableModel de = (DefaultTableModel) tbdoanhthu.getModel();
        de.setRowCount(0);
        for (HoaDonViewModels hd : hdservice.GetListHoaSon()) {
            de.addRow(new Object[]{
                hd.getMa(), hd.getNgayThanhToan(), hd.getTongTien(), hd.getTrangThai()
            });
        }
    }

    private void TongTien() {
        DecimalFormat x = new DecimalFormat("###,###,###");
        int Tong = 0;
        for (ThongKe hd : thongkeser.finByBieuDo()) {
            Tong += hd.getTien();
        }
        lbltong.setText(x.format(Tong) + "" + " VND");
        lblTHD.setText(hdservice.GetListHoaSon().size() + " " + " Đơn ");
        lblhdHuy.setText(hdservice.finbyngaytrangThai(2).size() + " " + " Đơn ");
        lblhdThanhcong.setText(hdservice.finbyngaytrangThai(5).size() + " " + " Đơn ");
        lblTongDHT.setText(hdservice.finbyngaytrangThai(4).size() + " " + " Đơn ");
    }

    private void NamHienNay() {
        DecimalFormat x = new DecimalFormat("###,###,###");
        int Nam = 0;
        LocalDate late = LocalDate.now();
//
//            SimpleDateFormat simpleDateFormat = new SimpleDateFormat();
//            simpleDateFormat.applyPattern("yyyy");
//            String Nam = simpleDateFormat.format(date);
        int nam = late.getYear();

        lblTHDNam.setText(thongkeser.finByNgayThanhToanNam(nam).size() + " " + " Đơn ");
        lblDTNamThanhcong.setText(thongkeser.finByNgayThanhToannamandTT(nam, 5).size() + " " + " Đơn ");
        lblNamDHT.setText(thongkeser.finByNgayThanhToannamandTT(nam, 4).size() + " " + " Đơn ");
        lblDTNamHuy.setText(thongkeser.finByNgayThanhToannamandTT(nam, 2).size() + " " + " Đơn ");
        List<ThongKe> list = thongkeser.finTongtienByNgayThanhToanNam(nam);
        for (ThongKe hd : list) {
            Nam += hd.getTien();

        }
        lblnam.setText(x.format(Nam) + "" + " VND");

    }

    public void thangHienTai() {
        DecimalFormat x = new DecimalFormat("###,###,###");
        int Thang = 0;
        LocalDate late = LocalDate.now();
        int nam = late.getYear();
        int thang = late.getMonth().getValue();
        lblTHDThang.setText(thongkeser.finbyngaythanhToanThang(thang).size() + " " + " Đơn ");
        lblDTThangThanhcong.setText(thongkeser.finByNgayThanhToaThangnandTT(thang, 5).size() + " " + " Đơn ");
        lblDTThangHuy.setText(thongkeser.finByNgayThanhToaThangnandTT(thang, 2).size() + " " + " Đơn ");
        lblThangDHT.setText(thongkeser.finByNgayThanhToaThangnandTT(thang, 4).size() + " " + " Đơn ");

        List<ThongKe> listthang = thongkeser.finbyTongtienngaythanhToanThang(thang);
        for (ThongKe hd : listthang) {
            Thang += hd.getTien();

        }
        lblthang.setText(x.format(Thang) + "" + " VND");
    }

    public void ngayHienTai() {
        DecimalFormat x = new DecimalFormat("###,###,###");
        int Ngay = 0;
        LocalDate late = LocalDate.now();
        int ngay = late.getDayOfMonth();
        lblTHDNgay.setText(thongkeser.finbyngaythanhToanNgay(ngay).size() + " " + " Đơn ");
        lblDTNgayThanhcong.setText(thongkeser.finByNgayThanhToanandNgay(ngay, 5).size() + " " + " Đơn ");
        lblDTNgayHuy.setText(thongkeser.finByNgayThanhToanandNgay(ngay, 2).size() + " " + " Đơn ");
        lblNgayDHT.setText(thongkeser.finByNgayThanhToanandNgay(ngay, 4).size() + " " + " Đơn ");
        List<ThongKe> listngay = thongkeser.finbyTongtienngaythanhToanNgay(ngay);
        for (ThongKe hd : listngay) {
            Ngay += hd.getTien();
        }
        lblngay.setText(x.format(Ngay) + "" + " VND");

    }
    //==Bieu đồ

    public void setdatetoChar(JPanel jpanl) {

        List<ThongKe> list = thongkeser.finByBieuDo();
        if (list != null) {
            DefaultCategoryDataset dataset = new DefaultCategoryDataset();
            for (ThongKe hd : list) {
                dataset.addValue(hd.getTien(), "", hd.getNgay());
            }
            JFreeChart chart = ChartFactory.createBarChart("Biểu Đồ", "Thời Gian", "Doang Thu", dataset);
            ChartPanel chartpanel = new ChartPanel(chart);
            chartpanel.setPreferredSize(new Dimension(jpanl.getWidth(), 300));

            jpanl.removeAll();
            jpanl.setLayout(new CardLayout());
            jpanl.add(chartpanel);
            jpanl.validate();
            jpanl.repaint();
        }

    }

    public void loadTableSPsapHet() {
        DefaultTableModel de = (DefaultTableModel) tblThongKeSP.getModel();
        de.setRowCount(0);
        for (ThongKeViewModel tk : thongkeser.getAllSanPhamThongKe()) {

            de.addRow(new Object[]{
                tk.getMa(), tk.getTenSp(), tk.getTenMausac(),
                tk.getTenNcc(), tk.getTenNsx(), tk.getTenHang(),
                tk.getSoLuong(), tk.getSize(), tk.getGiaban(), tk.getGiaNhap()

            });
        }
    }

    private void finByKhoangNgayThanhToan(Date ngay, Date ngay2) {
        DefaultTableModel de = (DefaultTableModel) tbdoanhthu.getModel();
        de.setRowCount(0);
        if(hdservice.finByKhoangNgayThanhToan(ngay, ngay2).size()>0 ){
            
        if(txtngayBD.getDate() != null || txtngayKT.getDate() != null){
                for (HoaDonViewModels hd : hdservice.finByKhoangNgayThanhToan(ngay, ngay2)) {
                    de.addRow(new Object[]{
                        hd.getMa(), hd.getNgayThanhToan(), hd.getTongTien(), hd.getTrangThai()
                    });
                }
            } else{
                JOptionPane.showMessageDialog(this, "Mời chon ngày bắt đầu hoặc ngày kết thúc ");
            }
    }else{
         JOptionPane.showMessageDialog(this, "Không có doang thu bạn cần tìm. Mời bạn chọn lại ngày");
        if(txtngayBD.getDate() != null || txtngayKT.getDate() != null){
                for (HoaDonViewModels hd : hdservice.finByKhoangNgayThanhToan(ngay, ngay2)) {
                    de.addRow(new Object[]{
                        hd.getMa(), hd.getNgayThanhToan(), hd.getTongTien(), hd.getTrangThai()
                    });
                }
            } else{
                JOptionPane.showMessageDialog(this, "Mời chon ngày bắt đầu hoặc ngày kết thúc ");
            }
        }
    }
}
